### ISSUE TITLE
Independent inclusion of the conditioner

### ISSUE THREAD

**Issue by johngrinders** [XattSPT/com.melcloud#14]
Good day.
Previously, the air conditioner was set to automatic operation. Up to the fact that it was Flow that does not allow the air conditioner to turn on when the windows are open.
Today, after an automatic upgrade to v2.0.9 with open windows, I find that a message begins to arrive at a regular frequency of 2 minutes exactly about an attempt to turn on the air conditioning, which in principle should not be.
I turn off all Flow, which are connected with the air conditioner, and the air conditioner starts turning on itself, or rather, as I managed to notice, it shows in Homey that it is on, but in fact the air conditioner does not work. But if you turn it off and turn it on yourself, then the air conditioner will work.
From this, I concluded that somehow the plug-in is incorrect and it determines and sets the condition of the air conditioner without physically turning on the air conditioner itself.
Now, with all the Flow turned off, the air conditioner itself starts for 2-4 minutes and then turns off and turns on immediately.
Diagnostic Report: 0a453f5b-4ceb-4f1f-9b17-ad4d024d8d6f

**Comment by XattSPT** [comment]
Thanks, I'll take a look on the report.

I've corrected a bug on cold mode that on/off function was not showing correct status. I'll take a look on auto also if I broke anything...

This bug is on homey status (on/off) but does not turn your device on or off.

Try to publish a test version on weekend...

**Comment by johngrinders** [comment]
Greetings.  As previously said, flow is configured when the air conditioner cannot be turned on when the windows are closed.  And over the past couple of days I began to notice that the air conditioner works with the windows open for some reason.  Now I watched and realized that not only the status is changing in the plugin, but it really turns on the air conditioner, even with my flow in which when the air conditioner is turned on, the status of open windows is checked and if everything is ok, the air conditioner immediately turns off.  Now the status of the air conditioner changes almost every 2 minutes and this flow turns the air conditioner out of 20 times, but this flow works 20 times, but for some reason it does not turn off the air conditioner.  And then the air conditioner turns on by itself.  Below is a report and a photo of regular attempts to turn on with only one flow, which I wrote about above.
1ec398ff-b073-4b8b-86aa-fd71cb2e072b
![70AB60BB-70B0-4E28-AC3D-7B603236119B](https://user-images.githubusercontent.com/13437063/83339523-6edf0780-a2d7-11ea-9213-5a40d73d168b.png)

**Comment by XattSPT** [comment]
I think i found the bug. Are U using auto mode and off mode, right?

I’ll try to solve it this weekend.

Sorry for inconvenience!

If I do not found a solution, I’ll publish a test with old config to avoid
problems.

El ds, 30 maig 2020 a les 23:41 johngrinders <notifications@github.com> va
escriure:

**Comment by johngrinders** [comment]
Hey.  Thank you for the melcloud plugin !!!  I use the modes from “set full mode” and only ventilation, cooling and heating.  I have never used automatic mode before, neither in manual mode nor through the plugin.  Now everything has become strange at all, I see that the air conditioner in homey is off, I go into the air conditioner itself, the power button is on, the fan mode is selected, and in the history of events it is off.  there is a small video on the link.  As there will be test versions, I can easily install it not through the store, for verification and testing.


https://share.icloud.com/photos/0mJFOHS5IbgECirpBYHUYp2Lg

**Comment by XattSPT** [comment]
@johngrinders 

I've published a new test version on https://homey.app/a/com.mecloud/test/

I think i found the bug, one character was missing, grrrr!!! Hope this works.

**Comment by johngrinders** [comment]
Already as 5 hours all Flow are turned off, the air conditioning device in homey itself changes its state every 5 minutes, without actually turning on the air conditioner.  The fact that earlier from such inclusions it was incorrect to work out the flow, therefore, this led to the inclusion of the air conditioner.

**Comment by XattSPT** [comment]
Can you send me a diagnostic report? I’ve added some console log to
investigate further.

El dg, 31 maig 2020 a les 15:18 johngrinders <notifications@github.com> va
escriure:

**Comment by johngrinders** [comment]
Hey. Installed a test version, everything began to work fine. Now the status itself does not change, like 1.5 hours. Now I’ll test with my previously written Flow. Thank you so much!!!

**Comment by johngrinders** [comment]
I'll test a couple more days, if there are any problems, unsubscribe.

**Comment by XattSPT** [comment]
Thanks for all of your bug reports, tests and collaboration.

Happy to see now it works!

**Comment by johngrinders** [comment]
Today I discovered an independent change in set full mode. Namely, if through the files I turn off the air conditioner from FAN mode, then after turning off the air conditioner, namely, setting the set full mode to OFF, after 5 minutes the FAN mode is set. And this happens with any mode that was turned on before shutting down. In fact, this affects some flow, in which the set full mode state is determined. I also noticed the following: I used to turn off the air conditioner through flow or through the power button and at the same time the air conditioner automatically switched to OFF mode in set full mode. Now, when the air conditioner is turned off, the set full mode remains unchanged.

**Comment by XattSPT** [comment]
@johngrinders  I've published a new test on 
   https://homey.app/a/com.mecloud/test/
can you try it? I've made some changes on flows, I think this was the problem. Manual changes seems to work correctly, but I'm sure your flows will take app to next level of testing ;)

Thanks in advance,

G.

**Comment by johngrinders** [comment]
> @johngrinders Я опубликовал новый тест на
> [https://homey.app/a/com.mecloud/test/,](https://homey.app/a/com.mecloud/test/)
> можешь попробовать? Я сделал некоторые изменения в потоках, я думаю, что это была проблема. Ручные изменения, кажется, работают правильно, но я уверен, что ваши потоки выведут приложение на новый уровень тестирования;)
> 
> Заранее спасибо,
> 
> Г.

Thank you so much!!! Yesterday I installed a new test version. But for some reason, after turning off the air conditioner, namely, setting the "Full termostate mode" to OFF (I have all the flow switched to this mode when I turn it off), after a few minutes, the last operating mode of the COOL or FAN air conditioner is again set on its own, which was previously turned on without turning on the air conditioner itself. During the operation of the air conditioner, everything works fine.

**Comment by johngrinders** [comment]
Thank you so much!!! Yesterday I installed a new test version. But for some reason, after turning off the air conditioner, namely, setting the "Full termostate mode" to OFF (I have all the flow switched to this mode when I turn it off), after a few minutes, the last operating mode of the COOL or FAN air conditioner is again set on its own, which was previously turned on without turning on the air conditioner itself. During the operation of the air conditioner, everything works fine.

**Comment by johngrinders** [comment]
Hey. Still experiencing problems with spontaneous inclusion of air conditioning. This moment the mode changes even when the air conditioner is off. Is it possible to somehow fix a spontaneous regime change? I have all Flow turn off the air conditioner and stand in OFF mode, but in fact after 2-5 minutes the mode switches to another independently.
Thank!!!

**Comment by XattSPT** [comment]
"off mode" should not be used, you should use on/off function to turn off
the unit.

If you watch off mode it is not available on Melcloud app, so it gives some
problems, use on/off to turn off unit.

Mode "maintains the memory" of last mode in order to turn it on an off and
maintain desired mode as Melcloud does.

I think the problem is in your flows, if you share them we can try to find
a solution.
